services:
  baikal:
    container_name: baikal
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 256M
    env_file:
      - .env
    image: ckulka/baikal:nginx
    labels:
      - diun.enable=true
    networks:
      - cloudflared
    ports:
      - ${SERVICE_PORT}:80
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${SERVICE_FOLDER_CONFIG}:/var/www/baikal/config
      - ${SERVICE_FOLDER_DATA}:/var/www/baikal/Specific

networks:
  cloudflared:
    external: true
