services:
  syncthing:
    container_name: syncthing
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    env_file:
      - .env
    image: linuxserver/syncthing:latest
    labels:
      - diun.enable=true
    networks:
      - cloudflared
    ports:
      - ${SERVICE_PORT}:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${SERVICE_FOLDER_CONFIG}:/config
      - ${SERVICE_FOLDER_DATA}:/data

networks:
  cloudflared:
    external: true
