services:
  db:
    container_name: warracker_db
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    image: postgres:15-alpine
    labels:
      - diun.enable=true
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${SERVICE_FOLDER_BACKUP}:/backups
      - ${SERVICE_FOLDER_DATA}:/var/lib/postgresql/data

  warracker:
    container_name: warracker
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 256M
    env_file:
      - .env
    image: ghcr.io/sassanix/warracker/main:latest
    labels:
      - diun.enable=true
    ports:
      - ${SERVICE_PORT}:80
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${SERVICE_FOLDER_UPLOADS}:/data/uploads
