services:
  jellyfin:
    container_name: jellyfin
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 1G
    env_file:
      - .env
    image: jellyfin/jellyfin:latest
    labels:
      - diun.enable=true
    ports:
      - ${SERVICE_PORT}:8096
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /dev/dri:/dev/dri
      - /dev/shm:/dev/shm
      - ${SERVICE_FOLDER_CONFIG}:/config
      - ${SERVICE_FOLDER_MEDIA}:/media
