services:
  redis:
    container_name: yamtrack-redis
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 64M
    image: redis:alpine
    networks:
      - yamtrack
    restart: unless-stopped
    volumes:
      - redis_data:/data

  yamtrack:
    container_name: yamtrack
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    env_file:
      - .env
    image: ghcr.io/fuzzygrim/yamtrack
    labels:
      - diun.enable=true
    networks:
      - cloudflared
      - yamtrack
    ports:
      - ${SERVICE_PORT}:8000
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${SERVICE_FOLDER_DATA}:/yamtrack/db

networks:
  cloudflared:
    external: true
  yamtrack:
    driver: bridge

volumes:
  redis_data:
