services:
  wallabag:
    container_name: wallabag
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 256M
    env_file:
      - .env
    image: wallabag/wallabag:latest
    labels:
      - diun.enable=true
    networks:
      - cloudflared
    ports:
      - ${SERVICE_PORT}:80
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${SERVICE_FOLDER_DATA}:/var/www/wallabag/data
      - ${SERVICE_FOLDER_IMAGES}:/var/www/wallabag/web/assets/images

networks:
  cloudflared:
    external: true
