services:
  hedgedoc:
    container_name: hedgedoc
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 256M
    env_file:
      - .env
    image: lscr.io/linuxserver/hedgedoc:alpine
    labels:
      - diun.enable=true
    networks:
      - cloudflared
    ports:
      - ${SERVICE_PORT}:3000
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${SERVICE_FOLDER_CONFIG}:/config
      - ${SERVICE_FOLDER_DATA}:/hedgedoc/data
      - ${SERVICE_FOLDER_UPLOADS}:/hedgedoc/public/uploads

networks:
  cloudflared:
    external: true
