services:
  diun:
    container_name: diun
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 32M
    env_file:
      - .env
    image: crazymax/diun:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${SERVICE_FOLDER_DATA}:/data
      - /var/run/docker.sock:/var/run/docker.sock
