services:
  duplicati:
    container_name: duplicati
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    env_file:
      - .env
    image: lscr.io/linuxserver/duplicati:latest
    labels:
      - diun.enable=true
    ports:
      - ${SERVICE_PORT}:8200
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${SERVICE_FOLDER_BACKUPS}:/backups
      - ${SERVICE_FOLDER_CONFIG}:/config
      - ${SERVICE_FOLDER_SOURCE}:/source:ro
